### ISSUE TITLE
自动存储日志

### ISSUE THREAD

**Issue by liucg1995** [luoyangpeng/action-log#1]
现在只有使用save() 进行添加修改的时候，才会自动记录日志，如何在使用 insert，update的时候也能自动记录日志呢？？

**Comment by luoyangpeng** [comment]
自动记录是用的Laravel里面ORM的事件。insert和update是没有触发事件的。你插入数据可以用save 和create。当然你也可以手动记录日志，为什么一定纠结要用insert和update呢。
